apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
