name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: maheshtodkar/myresume-website:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2 with KIND
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/myproject
          sudo git pull origin main
          sudo kubectl apply -f secrets.yaml
          sudo kubectl apply -f deployment.yaml
          sudo kubectl apply -f service.yaml
          sudo kubectl get pods
          sudo kubectl get services
    



    
